### ISSUE TITLE
Max Int and Min Int get reset every time

### ISSUE THREAD

**Issue by chiahaoliu** [NSLS-II-XPD/xpdView#23]
When trying to set max int by entering numeric value directly, this value gets updated but when I trying to set min int with numeric value, value at max int was rest to 346287 automatically. Same situation happens the other way around.

**Comment by cduff4464** [comment]
This happens whenever the Int min goes above int max in value. Since the intensity range automatically updates this has to always be in check or the plot would crash.

**Comment by cduff4464** [comment]
That explains the second one. I'm not too sure about the first one though.

**Comment by chiahaoliu** [comment]
I think it automatically updates max int or min int when I do with absolute scale, or maybe because some error in qt-messenger.  Here are more details on what happen:

(max_int, min_int) of pic = (2.6e4, 0)

1) when I set min_int as 45, it took it and then I set max_int to 2500, min_int was reset to -346287.680 
2) when I set max_int as 2500, it took it but when I set min_int to 45, max_int was reset to 346287.680

I can reproduce the bug in person tomorrow too.

**Comment by cduff4464** [comment]
Okay yeah I know what you are talking about. This is an X-ray_vision problem in that case. I don't have much control over that. I know that it constantly checks to ensure that min is always lower than max, and if it finds a contradiction it set min to the lowest possible value. This is because it is dynamically updating the image scaling when you use this option so the figure would crash if it did not check for this.

**Comment by cduff4464** [comment]
@chiahaoliu but yeah, we can talk more in person

**Comment by cduff4464** [comment]
This is a problem inherent to X-ray_vision. I have posted an issue there and it will have to be resolved on their end.
